---
on:
  push:
    branches:
      - main
name: 🚀 Deploy Dimaco
jobs:
  web-deploy:
    name: 🎉 Deploy Dimaco
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/scdimaco/publlic_html/
        
